### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by tintinmar1995**
Complete translation of the app in French. 

However, I could not build to app and check how relevent the translation is.

### CODE REVIEW

**Comment by Spikatrix** [comment]
Could you please translate the [Play Store variant strings](https://github.com/Spikatrix/LRC-Editor/blob/master/app/src/playstore/res/values/strings.xml) and the [F-Droid variant strings](https://github.com/Spikatrix/LRC-Editor/blob/master/app/src/fdroid/res/values/strings.xml) as well?

Also, feel free to add your name in the [Translators section](https://github.com/Spikatrix/LRC-Editor/blob/master/README.md#translators) in the README file

**Comment by tintinmar1995** [comment]
> 
> 
> Could you please translate the [Play Store variant strings](https://github.com/Spikatrix/LRC-Editor/blob/master/app/src/playstore/res/values/strings.xml) and the [F-Droid variant strings](https://github.com/Spikatrix/LRC-Editor/blob/master/app/src/fdroid/res/values/strings.xml) as well?
> 
> Also, feel free to add your name in the [Translators section](https://github.com/Spikatrix/LRC-Editor/blob/master/README.md#translators) in the README file

Sorry, I took some time before finishing the job. It's done now :)

**Comment by Spikatrix** [comment]
No worries! But it looks like you forgot to translate the [Play Store variant strings](https://github.com/Spikatrix/LRC-Editor/blob/master/app/src/playstore/res/values/strings.xml). Can you please do that as well?

**Comment by tintinmar1995** [comment]
My bad. Forgot to commit the file.

Envoyé depuis ProtonMail mobile

-------- Message d'origine --------

**Comment by Spikatrix** [comment]
Thank you! I'll review and pull the changes soon!

**Pull request merged**
